# должна быть совместима с пунктом 5
version: "3.8"

services:
  course_db:
    image: "postgres:latest"
    volumes:
      # адрес в хосте : адрес в контейнере
      - ./data:/var/lib/postgresql/data
    ports:
      # порт в хосте : порт в контейнере
      - "5050:5432"
    environment:
      - POSTGRES_USER=mipt
      - POSTGRES_PASSWORD=mipt
      - POSTGRESQL_PASSWORD=mipt